sudo: false
language: r
cache: packages
  
install:
  - R -e "install.packages('rmarkdown')"
  - R -e "install.packages('RPostgreSQL')"
  - R -e "install.packages('dplyr')"
  - R -e "install.packages('ggplot2')"
script:
  - R -e "rmarkdown::render('analysis.Rmd', output_file='index.html')" --args "$DBUSER" "$DBPASSWORD"
  
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  file: index.html
  on:
    branch: master
